#!/usr/bin/zsh

# update dnf
echo "Updating dnf packages..."
sudo dnf -y update

# upgrade dnf
echo "Upgrading dnf packages..."
sudo dnf -y upgrade

# clean up dnf
echo "Cleaning up unused dnf dependencies..."
sudo dnf -y autoremove

# clear dnf cache
echo "Clearing dnf cache..."
sudo dnf -y clean all

# update oh-my-zsh
echo "Updating oh-my-zsh..."
ZSH='/home/neal/.oh-my-zsh'
zsh "$ZSH/tools/upgrade.sh"

# initialize zinit for this shell
source "/home/neal/.local/share/zinit/zinit.git/zinit.zsh"

# update zinit
echo "Updating zinit..."
zi self-update

# update zinit plugins
echo "Updating zinit plugins..."
zi update --parallel

# update rust install via rustup
echo "Updating rust..."
rustup update

# update homebrew
echo "Updating Homebrew..."
brew update

# upgrade brew packages
echo "Upgrading Homebrew CLI tools..."
brew upgrade

# upgrade brew casks
echo "Upgrading Homebrew casks..."
brew upgrade --cask

# clean up old brew packages
echo "Cleaning up old Homebrew package versions..."
brew cleanup

# restart any homebrew background services
echo "Restarting Homebrew services..."
brew services restart --all

# confirm brew system integrity
echo "Running brew doctor..."
brew doctor
